# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  project_sort_config = debug

else ifeq ($(config),release)
  project_sort_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := project-sort

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

project-sort:
ifneq (,$(project_sort_config))
	@echo "==== Building project-sort ($(project_sort_config)) ===="
	@${MAKE} --no-print-directory -C . -f project-sort.make config=$(project_sort_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f project-sort.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   project-sort"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"